# Generated by Django 5.0.6 on 2024-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=255, verbose_name='CÓDIGO')),
                ('matetial_name', models.CharField(max_length=255, verbose_name='MATERIAL')),
                ('material_type', models.CharField(max_length=255, verbose_name='TIPO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
